### ISSUE TITLE
Add tests to components

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/d2-ui-components#1]
In EyeSeeTea/vaccination-app/issues/32 we are moving generic components from vaccination-app. Now we need tests. Jest for sure, maybe cypress in a second stage. I just created a simple test for DatePicker to setup the jest/ts infrastructure. Tasks:

- [ ] Create jest tests for all components (with snapshots?)

Ideas to be discussed:

- Convert components from jsx to tsx (that's only done for DatePicker, to test the TS infrastructure). Usually this involves creating types for state and props, for most components shouldn't be too costly.
- Cypress tests for components (2nd phase)

**Comment by adrianq** [comment]
Closing this. We will have this discussion at the right moment
