### ISSUE TITLE
Remove old objects-table

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/d2-ui-components#115]
This way we can remove the heavy and burdensome node-sass library.

We can keep a branch with the old objects table (should we ever need an update on old projects using it), and publish in a different channel.

**Comment by SferaDev** [comment]
LGTM. I wouldn't keep the old table in a different channel, just remove it and update the semver with a breaking change (updating the minor version 1.1.0?).

On ``metadata-sync`` we still have 3 usages that need refactor, but we have an issue tracking that and could be done with a small effort.

If we have a feature request on ``vaccination-app`` we should account for the migration to the new table where needed.

**Comment by tokland** [comment]
Ok! Not a priority, but the other day I had to fight with the rebuild of node-sass and it was not nice.
