### ISSUE TITLE
Improve Object Selection

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/d2-ui-components#12]
When a re-render happens ObjectsTable forgets about previously selected items.

Proposal: Move selection id array out of ObjectsTable and make it a required prop. That way it will be block-captured and the selection will persist across re-renders.

This proposal has the side-benefit of being able to read the currently selected items outside Objects Table and perform other operations as metadata-sync requires.

Added this issue outside the Improvements card because of its severity.

**Comment by adrianq** [comment]
- [ ] Improve select all
   - [ ] When clicking on select all display a link saying something like 'Select all in all pages'
   - [ ] If the user clicks on 'Select all in all pages' the link should change to 'Select all in first page'
   - [ ] For clear all the user should click on the checkbox again

**Comment by SferaDev** [comment]
I did a couple of attempts to achieve this but there's no trivial implementation and I'd like to discuss with the rest about what's the best approach for this.

For reference, logic-wise:

- Add a new method that lists all IDs from model. (Don't recommend for complexity)

- Re-use the existing listMethod and allow paging false. (metadata-sync already prepared to accept the flag as of #60)

- Persistence of selection in selected in all pages, should be lost or not if you move from pages?


For reference, UX-wise:

- Since we are adding a note that allows to select in all pages/clean selection. We could re-use this for not erasing selection on previous page (something like: You selected 5 items in other pages. Clear selection").


I'm moving the issue back to the backlog and setting M2 as target milestone. We can discuss it in the next weekly meeting all together. I know that we already did a first discussion draft but there are more topics that might need consensus before implementing.

**Comment by SferaDev** [comment]
![Screenshot from 2019-04-11 14-35-26](https://user-images.githubusercontent.com/2181866/55958047-0f074680-5c68-11e9-9bf0-d56b09f9b978.png)

![Screenshot from 2019-04-11 14-35-38](https://user-images.githubusercontent.com/2181866/55958068-1af30880-5c68-11e9-9e7a-f8b4bfedf599.png)
