### ISSUE TITLE
[ObjectsTable] Complete property 'selectable' for rows

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/d2-ui-components#120]
Currently, the prop `selectable=false` is used to highlight the row and disable its checkbox, but that's not enough, there are other instances where a row can be selected/unselected:

- [ ] Checkbox Select/Unselect all
- [ ] There are {{total}} items selected in all pages -> Clear
- [ ] There are {{count}} items selected ({{invisible}} on other pages) -> Clear
- [ ] Select all {{total}} items in all pages -> Select all

At the moment, project-monitoring-app makes sure unselectable ids are not modified, but the table component should take care of it.

**Comment by adrianq** [comment]
Moved to clickup
