### ISSUE TITLE
[OrgUnitSelector] Refactor props.selectableLevels

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/d2-ui-components#134]
`props.selectableLevels` is used both to decide if an orgUnit shows the selectable input (that's ok), but also hides its children if their level is greater than `max(...selectableLevels)`, which is very dubious. Discuss the best approach.

(Don't forget to check that the filter in `getRoots` makes sense with those changes)

**Comment by adrianq** [comment]
Closing for now. The objective is the medium term would be to completely refactor the org unit selector
