### ISSUE TITLE
Investigate replacement of moment

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/d2-ui-components#178]
- Moment is being deprecated
- We have some usages to the library, find alternatives
- We do not seem to expose and type from their library so there shouldn't be any breaking changes user-facing

**Comment by adrianq** [comment]
In case it helps this a sort of thread twitter discussion re moment.js bein deprecated -> https://twitter.com/wesbos/status/1305846354791542785?s=20

**Comment by SferaDev** [comment]
Yes, I saw that thread too. Alternatives so far:

- String representation: ``Intl`` language support
- Date/time manipulation: ``date-fns`` or ``luxon``
- Full language support: ``Temporal`` still on stage 2 TC39 discussion... Once staged-3 when can consider it, if TS implements it timely

**Comment by adrianq** [comment]
Moved to clickup
