### ISSUE TITLE
material-ui/pickers dependencies

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/d2-ui-components#194]
We should add package to `dependencies` or `peerDependencies`. @SferaDev, what's your take?

**Comment by SferaDev** [comment]
To me the rule would be the following: ``if a module is used in d2-ui-components and does not conflict if the app has a different version (due contexts, etc...) it should be added as a dependency``. So material-ui/pickers would be a dependency and not peerDependency.

**Comment by tokland** [comment]
Agreed. With some material-ui modules there are compatibility problems with the core, but let's try this first in normal/dev mode. I'll prepare a PR.
