### ISSUE TITLE
OrgUnitSelector checkboxes color

### ISSUE THREAD

**Issue by matiasgarcia91** [EyeSeeTea/d2-ui-components#36]
Currently, when selecting a higher level OrgUnit checkboxes for the lower level OrgUnits become barely visible. We should change the checkboxes color to black.
![image](https://user-images.githubusercontent.com/15323369/57614881-9e12c180-757a-11e9-8544-37310794f242.png)

I've tried applying styles to higher divs and overriding Mui styles but had no success so I've added a CSS rule in vaccination to temporarily take care of this. https://github.com/EyeSeeTea/vaccination-app/pull/141
Also, `@dhis2/d2-ui-org-unit-tree` receives a prop called `checkboxColor` but that only applies to the checked checkbox color.

**Comment by adrianq** [comment]
This was already solved a long time ago when we were young and full of life...
