### ISSUE TITLE
Future tasks

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/d2-ui-components#67]
- [x] snackbar/loading: investigate using a portal (+with render function in component itself) and no context/provder. Both modes (context and no-context) would be available.
- [x] Update to material-ui v4 -> #74
- [ ] Add HelpButton from apps
- [ ] Add PageHeader from apps
- [ ] Add ExitWizardButton from apps

**Comment by adrianq** [comment]
Moved to clickup
