### ISSUE TITLE
Components to abstract

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/d2-ui-components#8]
High Priority
- [x] [Migrate] Confirmation dialog (metadata-sync has the latest changes). See https://github.com/EyeSeeTea/vaccination-app/blob/development/src/components/confirmation-dialog/ConfirmationDialog.jsx
   - [x] Add optional props for button labels
   - [x] Integrate new confirmation dialog into dialog handler. Substitute Dialog component in render
   - [x] Rename components:
      Dialog Handler -> DialogButton
      Confirmation Dialog -> ConfirmationDialog

Low Priority
- [x] [Migrate] Wizard (from vaccination-app)
- [ ] [Improvement] expose DataTable: (clean up props -specially actions, should be as simple as ObjectsTable-, expose it in index.ts, and add docs to README).

**Comment by adrianq** [comment]
Not relevant anymore. We are currently following a different approach in most of the projects
